#!/bin/bash

source=~/Documents/java\ workspace/RoadRunner/src/tools/syncBlockStats

cp "$source"/SyncBlocksStats.java classes
cd classes
javac SyncBlocksStats.java
mv SyncBlocksStats.java ../src/tools/syncBlockStats
mv SyncBlocksStats*.class tools/syncBlockStats
cd ..