#!/bin/bash

source=~/Documents/java\ workspace/RoadRunner/src
file=
if [ $1 == "-t" ] 
    then 
       source=~/Documents/java\ workspace/RoadRunner/Tests
       if [ $2 ]
       then file=${2//.//}
       else echo "Must give file name."
       fi
    else 
       if [ $1 ]
       then file=${1//.//}
       else echo "Must give file name."
       fi
fi

cp "$source"/"$file".java src
cd src

toCompile=${file##*/}
javac $toCompile.java

potentialDest=${file%/*}
dest=
if [ $potentialDest == $file ]
then 
    dest=""
else dest=$potentialDest
fi


mv $toCompile.java Targets/$dest
mv $toCompile*.class Targets/$dest
cd ..