#!/bin/bash

source=~/Documents/java\ workspace/RoadRunner/src
file=
if [ $1 == "-t" ] 
    then 
       source=~/Documents/java\ workspace/RoadRunner/Tests
       if [ $2 ]
       then file=$2
       else echo "Must give file name."
       fi
    else 
       if [ $1 ]
       then file=$1
       else echo "Must give file name."
       fi
fi

cp "$source"/"$file".java src
cd src
javac "$file".java
mv "$file".java Targets
mv "$file"*.class Targets
cd ..