#! /bin/bash

no_verify="-cp DaCapo -noverify"
new_JVM_ARGS=$JVM_ARGS" "$no_verify
export JVM_ARGS=$new_JVM_ARGS



rrArgs="-array=FINE -classes=-SyncBlocksStats.* -classes=-Harness -classes=-org.dacapo.harness.* -classes=-org.dacapo.parser.* -classes=-TimerCallback"
forTomcat="-multiLoader -shadowThread=-.* -maxTid=64"
forLusearch="-maxTid=64"

bm=$1

if [ $bm == "tomcat" ]
   then rrArgs=$rrArgs" "$forTomcat
fi

if[ $bm == "lusearch" ]
    then rrArgs=$rrArgs" "$forLusearch
fi

rrrun $rrArgs -toolpath=classes/tools/trials -classpath=./DaCapo/dacapo-9.12-bach.jar -tool=SyncBlocksStats Harness $bm