#!/bin/bash

if [ "$1" ]
then
    if [ "$2" ]
    then rrrun -classes="-.*TeeOutputStream.*" -classpath="./DaCapo" -toolpath="./classes/tools/trials" -tool="$1" Harness "$2"
    else echo "Need two arguments"
    fi
else echo "Need two arguments"
fi


